1. Найти с помощью NumPy SVD для матрицы

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$


In [6]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

A = np.array([[1, 2, 0],
              [0, 0, 5],
             [3, -4, 2],
             [1, 6, 5],
             [0, 1, 0]])

print(f'Матрица A:\n{A}\n')

U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'Матрица D:\n{D}\n')
print(f'Матрица U:\n{U}\n')

print("Убедимся, что она действительно ортогональна\n")
print(f"{np.dot(U.T, U)}\n")

print("Убедимся, что она действительно ортогональна\n")
print(f"{np.dot(V.T, V)}\n")

print("Проведем проверку\n")
print(np.dot(np.dot(U, D), V.T))

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Убедимся, что она действительно ортогональна

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]

Убедимся, что она действительно ортогональна

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]

Проведем проверку

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [16]:
print(f"Евклидова норма матрицы: {np.linalg.norm(A, 2)}")
print(f"Норма Фробениуса матрицы: {np.linalg.norm(A)}")


Евклидова норма матрицы: 8.824868854820444
Норма Фробениуса матрицы: 11.045361017187261
